import Sidebar from "@/components/Sidebar";
import "./../assets/css/fontawesome.min.css";
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'React Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex relative">
          <div className="grow-0">
            <Sidebar />
          </div>
          <div className="grow">
            {children}
          </div>

        </div>

      </body>
    </html>
  )
}
